config:
  target: "ws://127.0.0.1:8082/ws"
  ws:
    maxRedirects: 25
  phases:
    - duration: 15
      arrivalRate: 1
      rampTo: 50
      name: "Max load"
scenarios:
  - engine: "ws"
    flow:
      - send: "hello world"
      - receive: "You said: hello world"
      - send: "another message"
      - receive: "You said: another message"